<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0-windows10.0.19041.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../WeChatJevHud.Observer/WeChatJevHud.Observer.csproj" />
    <ProjectReference Include="../WeChatJevHud.Ocr.Windows/WeChatJevHud.Ocr.Windows.csproj" />
    <ProjectReference Include="../WeChatJevHud.Ocr.Tesseract/WeChatJevHud.Ocr.Tesseract.csproj" />
  </ItemGroup>
</Project>
